FROM node:23-alpine
WORKDIR /app

CMD \
  if [ -f yarn.lock ]; then yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && corepack use pnpm@10.8.1 && pnpm run dev; \
  else npm run dev; \
  fi